/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 59 countries!
 *
 * The version of the OpenAPI document: 3.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Country } from './Country';
import {
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
} from './Country';

/**
 * 
 * @export
 * @interface CountriesResponseSchema
 */
export interface CountriesResponseSchema {
    /**
     * Map of country code to country details.
     * @type {{ [key: string]: Country; }}
     * @memberof CountriesResponseSchema
     */
    result: { [key: string]: Country; };
}

/**
 * Check if a given object implements the CountriesResponseSchema interface.
 */
export function instanceOfCountriesResponseSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;

    return isInstance;
}

export function CountriesResponseSchemaFromJSON(json: any): CountriesResponseSchema {
    return CountriesResponseSchemaFromJSONTyped(json, false);
}

export function CountriesResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountriesResponseSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': (mapValues(json['result'], CountryFromJSON)),
    };
}

export function CountriesResponseSchemaToJSON(value?: CountriesResponseSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': (mapValues(value.result, CountryToJSON)),
    };
}

