/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 58 countries!
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenresResponseSchema
 */
export interface GenresResponseSchema {
    /**
     * Map of genre id to genre name.
     * @type {{ [key: string]: string; }}
     * @memberof GenresResponseSchema
     */
    result: { [key: string]: string; };
}

/**
 * Check if a given object implements the GenresResponseSchema interface.
 */
export function instanceOfGenresResponseSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;

    return isInstance;
}

export function GenresResponseSchemaFromJSON(json: any): GenresResponseSchema {
    return GenresResponseSchemaFromJSONTyped(json, false);
}

export function GenresResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenresResponseSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': json['result'],
    };
}

export function GenresResponseSchemaToJSON(value?: GenresResponseSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
    };
}

