/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 59 countries!
 *
 * The version of the OpenAPI document: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Show } from './Show';
import {
    ShowFromJSON,
    ShowFromJSONTyped,
    ShowToJSON,
} from './Show';

/**
 * 
 * @export
 * @interface GetResponseSchema
 */
export interface GetResponseSchema {
    /**
     * 
     * @type {Show}
     * @memberof GetResponseSchema
     */
    result: Show;
}

/**
 * Check if a given object implements the GetResponseSchema interface.
 */
export function instanceOfGetResponseSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;

    return isInstance;
}

export function GetResponseSchemaFromJSON(json: any): GetResponseSchema {
    return GetResponseSchemaFromJSONTyped(json, false);
}

export function GetResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetResponseSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': ShowFromJSON(json['result']),
    };
}

export function GetResponseSchemaToJSON(value?: GetResponseSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': ShowToJSON(value.result),
    };
}

