/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Horizontal image of a show.
 * @export
 * @interface HorizontalImage
 */
export interface HorizontalImage {
    /**
     * Link to the 360px wide version of the image.
     * @type {string}
     * @memberof HorizontalImage
     */
    w360: string;
    /**
     * Link to the 480px wide version of the image.
     * @type {string}
     * @memberof HorizontalImage
     */
    w480: string;
    /**
     * Link to the 720px wide version of the image.
     * @type {string}
     * @memberof HorizontalImage
     */
    w720: string;
    /**
     * Link to the 1080px wide version of the image.
     * @type {string}
     * @memberof HorizontalImage
     */
    w1080: string;
    /**
     * Link to the 1440px wide version of the image.
     * @type {string}
     * @memberof HorizontalImage
     */
    w1440: string;
}

/**
 * Check if a given object implements the HorizontalImage interface.
 */
export function instanceOfHorizontalImage(value: object): boolean {
    if (!('w360' in value)) return false;
    if (!('w480' in value)) return false;
    if (!('w720' in value)) return false;
    if (!('w1080' in value)) return false;
    if (!('w1440' in value)) return false;
    return true;
}

export function HorizontalImageFromJSON(json: any): HorizontalImage {
    return HorizontalImageFromJSONTyped(json, false);
}

export function HorizontalImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HorizontalImage {
    if (json == null) {
        return json;
    }
    return {
        
        'w360': json['w360'],
        'w480': json['w480'],
        'w720': json['w720'],
        'w1080': json['w1080'],
        'w1440': json['w1440'],
    };
}

export function HorizontalImageToJSON(value?: HorizontalImage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'w360': value['w360'],
        'w480': value['w480'],
        'w720': value['w720'],
        'w1080': value['w1080'],
        'w1440': value['w1440'],
    };
}

