/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of an item.
 * @export
 */
export const ItemType = {
    Show: 'show',
    Season: 'season',
    Episode: 'episode'
} as const;
export type ItemType = typeof ItemType[keyof typeof ItemType];


export function instanceOfItemType(value: any): boolean {
    return Object.values(ItemType).includes(value);
}

export function ItemTypeFromJSON(json: any): ItemType {
    return ItemTypeFromJSONTyped(json, false);
}

export function ItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemType {
    return json as ItemType;
}

export function ItemTypeToJSON(value?: ItemType | null): any {
    return value as any;
}

