/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderDirection = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type OrderDirection = typeof OrderDirection[keyof typeof OrderDirection];


export function instanceOfOrderDirection(value: any): boolean {
    return Object.values(OrderDirection).includes(value);
}

export function OrderDirectionFromJSON(json: any): OrderDirection {
    return OrderDirectionFromJSONTyped(json, false);
}

export function OrderDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDirection {
    return json as OrderDirection;
}

export function OrderDirectionToJSON(value?: OrderDirection | null): any {
    return value as any;
}

