/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 59 countries!
 *
 * The version of the OpenAPI document: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Show } from './Show';
import {
    ShowFromJSON,
    ShowFromJSONTyped,
    ShowToJSON,
} from './Show';

/**
 * 
 * @export
 * @interface SearchTitleResponseSchema
 */
export interface SearchTitleResponseSchema {
    /**
     * Array of the shows matched with the title.
     * @type {Array<Show>}
     * @memberof SearchTitleResponseSchema
     */
    result: Array<Show>;
}

/**
 * Check if a given object implements the SearchTitleResponseSchema interface.
 */
export function instanceOfSearchTitleResponseSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "result" in value;

    return isInstance;
}

export function SearchTitleResponseSchemaFromJSON(json: any): SearchTitleResponseSchema {
    return SearchTitleResponseSchemaFromJSONTyped(json, false);
}

export function SearchTitleResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchTitleResponseSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': ((json['result'] as Array<any>).map(ShowFromJSON)),
    };
}

export function SearchTitleResponseSchemaToJSON(value?: SearchTitleResponseSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': ((value.result as Array<any>).map(ShowToJSON)),
    };
}

