/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 58 countries!
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Images of a service.
 * @export
 * @interface ServiceImages
 */
export interface ServiceImages {
    /**
     * Link to the logo of the service suitable for light themed background.
     * @type {string}
     * @memberof ServiceImages
     */
    lightThemeImage: string;
    /**
     * Link to the logo of the service suitable for dark themed background.
     * @type {string}
     * @memberof ServiceImages
     */
    darkThemeImage: string;
    /**
     * Link to the logo of the service that is all white.
     * @type {string}
     * @memberof ServiceImages
     */
    whiteImage: string;
}

/**
 * Check if a given object implements the ServiceImages interface.
 */
export function instanceOfServiceImages(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lightThemeImage" in value;
    isInstance = isInstance && "darkThemeImage" in value;
    isInstance = isInstance && "whiteImage" in value;

    return isInstance;
}

export function ServiceImagesFromJSON(json: any): ServiceImages {
    return ServiceImagesFromJSONTyped(json, false);
}

export function ServiceImagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceImages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lightThemeImage': json['lightThemeImage'],
        'darkThemeImage': json['darkThemeImage'],
        'whiteImage': json['whiteImage'],
    };
}

export function ServiceImagesToJSON(value?: ServiceImages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lightThemeImage': value.lightThemeImage,
        'darkThemeImage': value.darkThemeImage,
        'whiteImage': value.whiteImage,
    };
}

