/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Image set of a service or an addon.
 * @export
 * @interface ServiceImageSet
 */
export interface ServiceImageSet {
    /**
     * Link to the logo suitable for light themed background.
     * @type {string}
     * @memberof ServiceImageSet
     */
    lightThemeImage: string;
    /**
     * Link to the logo suitable for dark themed background.
     * @type {string}
     * @memberof ServiceImageSet
     */
    darkThemeImage: string;
    /**
     * Link to the logo that is all white.
     * @type {string}
     * @memberof ServiceImageSet
     */
    whiteImage: string;
}

/**
 * Check if a given object implements the ServiceImageSet interface.
 */
export function instanceOfServiceImageSet(value: object): boolean {
    if (!('lightThemeImage' in value)) return false;
    if (!('darkThemeImage' in value)) return false;
    if (!('whiteImage' in value)) return false;
    return true;
}

export function ServiceImageSetFromJSON(json: any): ServiceImageSet {
    return ServiceImageSetFromJSONTyped(json, false);
}

export function ServiceImageSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceImageSet {
    if (json == null) {
        return json;
    }
    return {
        
        'lightThemeImage': json['lightThemeImage'],
        'darkThemeImage': json['darkThemeImage'],
        'whiteImage': json['whiteImage'],
    };
}

export function ServiceImageSetToJSON(value?: ServiceImageSet | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lightThemeImage': value['lightThemeImage'],
        'darkThemeImage': value['darkThemeImage'],
        'whiteImage': value['whiteImage'],
    };
}

