/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of a show.
 * @export
 */
export const ShowType = {
    Movie: 'movie',
    Series: 'series'
} as const;
export type ShowType = typeof ShowType[keyof typeof ShowType];


export function instanceOfShowType(value: any): boolean {
    return Object.values(ShowType).includes(value);
}

export function ShowTypeFromJSON(json: any): ShowType {
    return ShowTypeFromJSONTyped(json, false);
}

export function ShowTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowType {
    return json as ShowType;
}

export function ShowTypeToJSON(value?: ShowType | null): any {
    return value as any;
}

