/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Availability API
 * Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Horizontal image of a show.
 * @export
 * @interface VerticalImage
 */
export interface VerticalImage {
    /**
     * Link to the 240px wide version of the image.
     * @type {string}
     * @memberof VerticalImage
     */
    w240: string;
    /**
     * Link to the 360px wide version of the image.
     * @type {string}
     * @memberof VerticalImage
     */
    w360: string;
    /**
     * Link to the 480px wide version of the image.
     * @type {string}
     * @memberof VerticalImage
     */
    w480: string;
    /**
     * Link to the 600px wide version of the image.
     * @type {string}
     * @memberof VerticalImage
     */
    w600: string;
    /**
     * Link to the 720px wide version of the image.
     * @type {string}
     * @memberof VerticalImage
     */
    w720: string;
}

/**
 * Check if a given object implements the VerticalImage interface.
 */
export function instanceOfVerticalImage(value: object): boolean {
    if (!('w240' in value)) return false;
    if (!('w360' in value)) return false;
    if (!('w480' in value)) return false;
    if (!('w600' in value)) return false;
    if (!('w720' in value)) return false;
    return true;
}

export function VerticalImageFromJSON(json: any): VerticalImage {
    return VerticalImageFromJSONTyped(json, false);
}

export function VerticalImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerticalImage {
    if (json == null) {
        return json;
    }
    return {
        
        'w240': json['w240'],
        'w360': json['w360'],
        'w480': json['w480'],
        'w600': json['w600'],
        'w720': json['w720'],
    };
}

export function VerticalImageToJSON(value?: VerticalImage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'w240': value['w240'],
        'w360': value['w360'],
        'w480': value['w480'],
        'w600': value['w600'],
        'w720': value['w720'],
    };
}

